.TH TemplateManPage 1
.SH NAME
TestTool - A little test tool for fun testing purposes
.SH SYPNOSIS
.B TestTool [-v] [-l
.I config-file
.B ]
.SH DESCRIPTION

This would be a more advanced description of the test tool.

.SH OPTIONS
.IP -v
A little information on the -v command
.IP "-l config-file"
A little explanation on the -l command which can be used with (
.I config-file
) when you are operating properly
.SH "EXAMPLES"
.IP "TestTool -v"
A little explanation
.IP "TestTool -l abc"
A little explanation
.SH BUGS
If you encounter bugs, please report them on my
git page under under https://mysite.com/gogs/
.SH AUTHOR
Firstname Lastname <email@email.com>
.SH COPYRIGHT
This piece of software is licensed under the test license.
.SH "SEE ALSO"
.BR reboot(8)
